### ISSUE TITLE
Error: viewport-mercator-project: assertion failed on _onPointerMove callback

### ISSUE THREAD

**Issue by wentsul** [uber/deck.gl#1961]
I have a `react-map-gl` application that uses `deck.gl` to render Arc and Path layers to show trips on a map. We're seeing a lot of client errors from our Windows/IE users of type `Error: viewport-mercator-project: assertion failed.`.

I'm currently using deck.gl 5.2.2 with react-map-gl `3.2.5`.

It looks like it comes from invalid events being passed to `_onPointerMove` in `core/lib/deck.js`. In the `_onClick` callback, invalid events are filtered out but they're not currently filtered out in `_onPointerMove`.

Here's an example stack trace:

```
Error: viewport-mercator-project: assertion failed.
  at _xyz2(../../node_modules/@deck.gl/core/node_modules/viewport-mercator-project/dist/es5/assert.js:13:1)
  at coord(../../node_modules/@deck.gl/core/node_modules/viewport-mercator-project/dist/es5/web-mercator-utils.js:346:1)
  at baseInfo(../../node_modules/@deck.gl/core/dist/es5/core/viewports/viewport.js:266:1)
  at (unknown)(../../node_modules/@deck.gl/core/dist/es5/core/lib/pick-layers.js:308:1)
  at (unknown)(../../node_modules/@deck.gl/core/dist/es5/core/lib/pick-layers.js:90:1)
  at selectedInfos(../../node_modules/@deck.gl/core/dist/es5/core/lib/layer-manager.js:464:1)
  at this(../../node_modules/@deck.gl/core/dist/es5/core/lib/layer-manager.js:1054:1)
  at handler(../../node_modules/@deck.gl/core/dist/es5/core/lib/layer-manager.js:1008:1)
  at handlers(../../node_modules/mjolnir.js/src/event-manager.js:281:11)
  at this(../../node_modules/hammerjs/hammer.js:2519:1)
  at (unknown)(../../node_modules/hammerjs/hammer.js:2128:1)
  at this(../../node_modules/hammerjs/hammer.js:1555:1)
  at recognizer(../../node_modules/hammerjs/hammer.js:1602:1)
  at manager(../../node_modules/hammerjs/hammer.js:2368:1)
  at this(../../node_modules/hammerjs/hammer.js:517:1)
  at oldHandler(../../node_modules/hammerjs/hammer.js:909:1)
  at self(../../node_modules/mjolnir.js/src/utils/hammer-overrides.js:46:5)
  at (unknown)(../../node_modules/hammerjs/hammer.js:430:1)
  at (unknown)(../../node_modules/raven-js/src/raven.js:353:1)
```

#### Actual Result

Calling `_pickAndCallback` triggers `Error: viewport-mercator-project: assertion failed.` due to event object not having `offsetCenter` property.

#### Expected Result

Do not call `_pickAndCallback` if `event.offsetCenter` is invalid.

#### Reproduce Steps

I have not been able to reproduce.

#### To Do List 
  - [x] Add label and assign to milestone
  - [x] Coding
  - [ ] Test

**Comment by 1chandu** [comment]
@wentsul , closing this since the PR is landed, re-open if there is any pending issue.

**Comment by hijiangtao** [comment]
@1chandu It seems I met the same problem when drawing scatterplot with recent released `deck.gl`.

```
layer-manager.js:704 deck: error while initializing ScatterplotLayer({id: 'scatterplot'})
 Error: deck.gl: assertion failed.
    at assert (assert.js:6)
    at ScatterplotLayer._initState (layer.js:1096)
    at ScatterplotLayer._initialize (layer.js:726)
    at LayerManager._initializeLayer (layer-manager.js:700)
    at LayerManager._updateSublayersRecursively (layer-manager.js:631)
    at LayerManager._updateSublayersRecursively (layer-manager.js:651)
    at LayerManager._updateLayers (layer-manager.js:581)
    at LayerManager.setLayers (layer-manager.js:269)
    at LayerManager.updateLayers (layer-manager.js:296)
    at Deck._onRenderFrame (deck.js:666)
```

I'm currently using deck.gl 6.4.4 with react-map-gl 4.0.6.
