### ISSUE TITLE
Cannot build webpack example for production

### ISSUE THREAD

**Issue by TPreece101** [uber/deck.gl#2266]
Hi, I am trying to build the deck.gl `react-webpack-2` get-started example for production and I am running into the following issue:
#### Actual Result
```
Error: Cannot find module '../../webpack.config.local'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (/Users/tom/Documents/test/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at module.exports.env (/Users/tom/Documents/test/webpack.config.js:46:32)
    at handleFunction (/Users/tom/Documents/test/node_modules/webpack-cli/bin/prepareOptions.js:23:13)
    at prepareOptions (/Users/tom/Documents/test/node_modules/webpack-cli/bin/prepareOptions.js:9:5)
    at requireConfig (/Users/tom/Documents/test/node_modules/webpack-cli/bin/convert-argv.js:136:14)
    at /Users/tom/Documents/test/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/tom/Documents/test/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/Users/tom/Documents/test/node_modules/webpack-cli/bin/webpack.js:240:39)
    at Object.parse (/Users/tom/Documents/test/node_modules/yargs/yargs.js:552:18)
    at /Users/tom/Documents/test/node_modules/webpack-cli/bin/webpack.js:218:8
    at Object.<anonymous> (/Users/tom/Documents/test/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/tom/Documents/test/node_modules/webpack/bin/webpack.js:165:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-webpack-2@0.0.0 build: 'NODE_ENV=production webpack --env.prod=true'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-webpack-2@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2018-09-09T18_14_59_771Z-debug.log
```
#### Reproduce Steps
I got to this error by doing the following steps:

1. Move the `react-webpack-2` to a new location outside the repo.

2. cd into the `react-webpack-2` folder

3. Run `npm install` 

4. Run `npm start` - runs just fine

5. Run `npm run-script build` 

 If am not entirely sure if I have missed something, any help would be appreciated. Thanks!

#### Code Example

**Comment by ibgreen** [comment]
> I got to this error by `npm run build`

Confirmed. The reason is that the production build uses `--env` which triggers the load of the local overrides.

To work around this, just delete the last line of the webpack config: https://github.com/uber/deck.gl/blob/master/examples/get-started/react-webpack-2/webpack.config.js#L45

Instead you should be able to add `mode: production` to the config.

```js
const CONFIG = {
  mode: 'production',

  entry: {
```

**Comment by TPreece101** [comment]
OK I have got it sorted now, I needed to rename the `app.js` to `index.js` and put it inside a folder in the route named `src` . Also rather than deleting the last line in the config it needs to be changed to: `module.exports = CONFIG` .
