### ISSUE TITLE
Examples not working on Linux Mint

### ISSUE THREAD

**Issue by simonrp84** [uber/deck.gl#2496]
#### Actual Result
This error:

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/eum/deck.gl/deck.gl/examples/get-started/react-without-map/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/home/eum/deck.gl/deck.gl/examples/get-started/react-without-map/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:776:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-without-map@0.0.0 start: `webpack-dev-server --progress --hot --open`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-without-map@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eum/.npm/_logs/2018-12-11T10_57_14_143Z-debug.log

#### Expected Result
A successful example when typing "npm start"
#### Reproduce Steps
Follow example here: http://deck.gl/#/documentation/getting-started/installation?section=running-the-examples
npm install deck.gl 
git clone git@github.com:uber/deck.gl.git
cd deck.gl
git checkout 6.0-release
cd deck.gl/examples/get-started/react-without-map
npm install
npm start

error message appears

**Comment by Pessimistress** [comment]
Can you try the 6.3-release branch?
