### ISSUE TITLE
alias script need to be improved

### ISSUE THREAD

**Issue by xintongxia** [uber/deck.gl#2654]
#### Description

Current `getSubmodules` in `alias.js` loop through all the folds under `deck.gl/modules/` directory. We should change the logic to only consider `modules` with a `package.json` file in them, instead of just looking at folders. 

```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '~/deck.gl/modules/s2-layers/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._resolveFilename (/Users/xintongxia/dev/deck.gl/node_modules/module-alias/index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at fs.readdirSync.forEach.item (/Users/xintongxia/dev/deck.gl/aliases.js:36:27)
    at Array.forEach (<anonymous>)
    at getSubmodules (~/deck.gl/aliases.js:33:4)
    at getAliases (~/deck.gl/aliases.js:51:22)
    at Object.<anonymous> (~/deck.gl/test/start.js:10:24).
```

#### Repro Steps
Create an empty fold inside `deck.gl/modules/`, then run `yarn test`.

**Comment by Pessimistress** [comment]
Well there should be a package.json if you add anything to modules/

**Comment by ibgreen** [comment]
The problem is when switching between branches that have different sets of modules. Even though git checkout of a branch that doesn't contain the new module removes the package.json in that module's folder, it can't remove the module folder itself because it contains gitignored `dist` and `node_modules` folders. This defunct folder then trips up the re-bootstrap process. When doing background work on new layer catalogs this becomes a small pain point.
