### ISSUE TITLE
IconLayer: Silent test failure in node tests (`document is not defined`).

### ISSUE THREAD

**Issue by ibgreen** [uber/deck.gl#2669]
1. Make sure icon layer does not crash under node.js
2. investigate why test case doesn't fail.

test log:

```
# IconLayerc#constructor
deck: error while initializing IconLayer({id: 'empty'})
 ReferenceError: document is not defined
    at IconManager.setProps (/Users/ib/Documents/deck.gl/modules/layers/src/icon-layer/icon-manager.js:180:38)
    at IconLayer.updateState (/Users/ib/Documents/deck.gl/modules/layers/src/icon-layer/icon-layer.js:152:19)
    at IconLayer._updateState (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer.js:540:12)
    at IconLayer._initialize (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer.js:511:10)
    at LayerManager._initializeLayer (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:504:13)
    at LayerManager._updateSublayersRecursively (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:455:16)
    at LayerManager._updateLayers (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:415:24)
    at LayerManager.setLayers (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:215:43)
    at doesNotThrow (/Users/ib/Documents/deck.gl/modules/test-utils/src/lifecycle-test.js:93:24)
    at checkDoesNotThrow (/Users/ib/Documents/deck.gl/modules/test-utils/src/lifecycle-test.js:34:12)
deck: error during update of IconLayer({id: 'empty'}) ReferenceError: document is not defined
    at IconManager.setProps (/Users/ib/Documents/deck.gl/modules/layers/src/icon-layer/icon-manager.js:180:38)
    at IconLayer.updateState (/Users/ib/Documents/deck.gl/modules/layers/src/icon-layer/icon-layer.js:152:19)
    at IconLayer._updateState (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer.js:540:12)
    at IconLayer._update (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer.js:529:12)
    at LayerManager._updateLayer (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:550:13)
    at LayerManager._updateSublayersRecursively (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:459:16)
    at LayerManager._updateLayers (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:415:24)
    at LayerManager.setLayers (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:215:43)
    at doesNotThrow (/Users/ib/Documents/deck.gl/modules/test-utils/src/lifecycle-test.js:137:26)
    at checkDoesNotThrow (/Users/ib/Documents/deck.gl/modules/test-utils/src/lifecycle-test.js:34:12)
deck: error while initializing IconLayer({id: 'null'})
 ReferenceError: document is not defined
    at IconManager.setProps (/Users/ib/Documents/deck.gl/modules/layers/src/icon-layer/icon-manager.js:180:38)
    at IconLayer.updateState (/Users/ib/Documents/deck.gl/modules/layers/src/icon-layer/icon-layer.js:152:19)
    at IconLayer._updateState (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer.js:540:12)
    at IconLayer._initialize (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer.js:511:10)
    at LayerManager._initializeLayer (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:504:13)
    at LayerManager._updateSublayersRecursively (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:455:16)
    at LayerManager._updateLayers (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:415:24)
    at LayerManager.setLayers (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:215:43)
    at doesNotThrow (/Users/ib/Documents/deck.gl/modules/test-utils/src/lifecycle-test.js:137:26)
    at checkDoesNotThrow (/Users/ib/Documents/deck.gl/modules/test-utils/src/lifecycle-test.js:34:12)
deck: error during update of IconLayer({id: 'null'}) ReferenceError: document is not defined
    at IconManager.setProps (/Users/ib/Documents/deck.gl/modules/layers/src/icon-layer/icon-manager.js:180:38)
    at IconLayer.updateState (/Users/ib/Documents/deck.gl/modules/layers/src/icon-layer/icon-layer.js:152:19)
    at IconLayer._updateState (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer.js:540:12)
    at IconLayer._update (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer.js:529:12)
    at LayerManager._updateLayer (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:550:13)
    at LayerManager._updateSublayersRecursively (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:459:16)
    at LayerManager._updateLayers (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:415:24)
    at LayerManager.setLayers (/Users/ib/Documents/deck.gl/modules/core/src/lib/layer-manager.js:215:43)
    at doesNotThrow (/Users/ib/Documents/deck.gl/modules/test-utils/src/lifecycle-test.js:137:26)
    at checkDoesNotThrow (/Users/ib/Documents/deck.gl/modules/test-utils/src/lifecycle-test.js:34:12)
ok 740 should update layer state
ok 741 should update layer state
ok 742 should add instancePositions64xyLow
# PathLayer#constructor
ok 743 should update layer state
ok 744 should update strokeWidth
# PolygonLayer#constructor
deck: error while initializing SolidPolygonLayer({id: 'PolygonLayer-fill'})
 Error: Vertex count exceeds browser index limit
    at TypedArrayManager._allocate (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:47:13)
    at TypedArrayManager.allocate (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:35:27)
    at PolygonTesselator._updateIndices (/Users/ib/Documents/deck.gl/modules/layers/src/solid-polygon-layer/polygon-tesselator.js:119:34)
    at PolygonTesselator.updateGeometryAttributes (/Users/ib/Documents/deck.gl/modules/layers/src/solid-polygon-layer/polygon-tesselator.js:101:10)
    at _forEachGeometry (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:173:12)
    at PolygonTesselator._forEachGeometry (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:116:7)
    at PolygonTesselator._rebuildGeometry (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:169:10)
    at PolygonTesselator.updateGeometry (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:86:10)
    at SolidPolygonLayer.updateGeometry (/Users/ib/Documents/deck.gl/modules/layers/src/solid-polygon-layer/solid-polygon-layer.js:188:25)
    at SolidPolygonLayer.updateState (/Users/ib/Documents/deck.gl/modules/layers/src/solid-polygon-layer/solid-polygon-layer.js:157:10)
deck: error during update of SolidPolygonLayer({id: 'PolygonLayer-fill'}) Error: Vertex count exceeds browser index limit
    at TypedArrayManager._allocate (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:47:13)
    at TypedArrayManager.allocate (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:35:27)
    at PolygonTesselator._updateIndices (/Users/ib/Documents/deck.gl/modules/layers/src/solid-polygon-layer/polygon-tesselator.js:119:34)
    at PolygonTesselator.updateGeometryAttributes (/Users/ib/Documents/deck.gl/modules/layers/src/solid-polygon-layer/polygon-tesselator.js:101:10)
    at _forEachGeometry (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:173:12)
    at PolygonTesselator._forEachGeometry (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:116:7)
    at PolygonTesselator._rebuildGeometry (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:169:10)
    at PolygonTesselator.updateGeometry (/Users/ib/Documents/deck.gl/modules/core/src/utils/tesselator.js:86:10)
    at SolidPolygonLayer.updateGeometry (/Users/ib/Documents/deck.gl/modules/layers/src/solid-polygon-layer/solid-polygon-layer.js:188:25)
    at SolidPolygonLayer.updateState (/Users/ib/Documents/deck.gl/modules/layers/src/solid-polygon-layer/solid-polygon-layer.js:157:10)
ok 745 should update layer state
ok 746 subLayers rendered
ok 747 should update state.paths
# geojson#import
ok 748 getGeojsonFeatures imported OK
```

**Comment by xintongxia** [comment]
> 2\. investigate why test case doesn't fail.

https://github.com/uber/deck.gl/blob/master/modules/test-utils/src/lifecycle-test.js#L98

I checked the `test-utils` module, it `doesNotThrow` error for initialization any layer.

Also noticed the same error for `SolidPolygonLayer` when running test.

```
deck: error while initializing SolidPolygonLayer({id: 'GeoJsonLayer-polygons-fill'})
 Error: Vertex count exceeds browser index limit
    at TypedArrayManager._allocate (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:47:13)
    at TypedArrayManager.allocate (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:35:27)
    at PolygonTesselator._updateIndices (/Users/xintongxia/dev/deck.gl/modules/layers/src/solid-polygon-layer/polygon-tesselator.js:119:34)
    at PolygonTesselator.updateGeometryAttributes (/Users/xintongxia/dev/deck.gl/modules/layers/src/solid-polygon-layer/polygon-tesselator.js:101:10)
    at _forEachGeometry (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:173:12)
    at PolygonTesselator._forEachGeometry (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:116:7)
    at PolygonTesselator._rebuildGeometry (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:169:10)
    at PolygonTesselator.updateGeometry (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:86:10)
    at SolidPolygonLayer.updateGeometry (/Users/xintongxia/dev/deck.gl/modules/layers/src/solid-polygon-layer/solid-polygon-layer.js:215:25)
    at SolidPolygonLayer.updateState (/Users/xintongxia/dev/deck.gl/modules/layers/src/solid-polygon-layer/solid-polygon-layer.js:184:10)
deck: error during update of SolidPolygonLayer({id: 'GeoJsonLayer-polygons-fill'}) Error: Vertex count exceeds browser index limit
    at TypedArrayManager._allocate (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:47:13)
    at TypedArrayManager.allocate (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:35:27)
    at PolygonTesselator._updateIndices (/Users/xintongxia/dev/deck.gl/modules/layers/src/solid-polygon-layer/polygon-tesselator.js:119:34)
    at PolygonTesselator.updateGeometryAttributes (/Users/xintongxia/dev/deck.gl/modules/layers/src/solid-polygon-layer/polygon-tesselator.js:101:10)
    at _forEachGeometry (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:173:12)
    at PolygonTesselator._forEachGeometry (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:116:7)
    at PolygonTesselator._rebuildGeometry (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:169:10)
    at PolygonTesselator.updateGeometry (/Users/xintongxia/dev/deck.gl/modules/core/src/utils/tesselator.js:86:10)
    at SolidPolygonLayer.updateGeometry (/Users/xintongxia/dev/deck.gl/modules/layers/src/solid-polygon-layer/solid-polygon-layer.js:215:25)
    at SolidPolygonLayer.updateState (/Users/xintongxia/dev/deck.gl/modules/layers/src/solid-polygon-layer/solid-polygon-layer.js:184:10)
```

**Comment by xintongxia** [comment]
> 1. Make sure icon layer does not crash under node.js

In `IconLayer`'s `initializeState`, it constructed an `IconManager` instance which requires `document`. So I am wondering can I stub the `IconManager` used in `IconLayer` testing?
