### ISSUE TITLE
I cannot install pydeck.

### ISSUE THREAD

**Issue by heumsi** [uber/deck.gl#3455]
Hi. I tried to install pydeck according to this [readme](https://github.com/uber/deck.gl/tree/master/bindings/python/pydeck)

I tried all, like these..
```
pip install pydeck
```
but the result was
```
ERROR: Could not find a version that satisfies the requirement pydeck (from versions: none)
ERROR: No matching distribution found for pydeck
```

and I tried this.
```
pip install -i https://test.pypi.org/simple/ pydeck
```
but
```
ERROR: Could not find a version that satisfies the requirement xarray>=0.10 (from pydeck) (from versions: none)
ERROR: No matching distribution found for xarray>=0.10 (from pydeck)
```

finally tried this.
```
# Clone the deck.gl repo
git clone https://github.com/uber/deck.gl/

# Navigate to the pydeck module
cd deck.gl/bindings/python/pydeck

# Create a virtual environment
virtualenv env
. env/bin/activate

python setup.py install
```
```
....
> webpack

sh: webpack: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @deck.gl/jupyter-widget@7.2.0-beta.3 notebook-bundle: `webpack`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @deck.gl/jupyter-widget@7.2.0-beta.3 notebook-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/heumsi/.npm/_logs/2019-08-16T01_04_34_204Z-debug.log
Traceback (most recent call last):
  File "setup.py", line 186, in <module>
    zip_safe=False)
  File "/Users/heumsi/anaconda3/envs/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Users/heumsi/anaconda3/envs/py36/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/heumsi/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/heumsi/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 51, in run
    self.distribution.run_command('jsdeps')
  File "/Users/heumsi/anaconda3/envs/py36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 117, in run
    check_call(['npm', 'run', 'notebook-bundle'], cwd=node_root, stdout=sys.stdout, stderr=sys.stderr, env=env)
  File "/Users/heumsi/anaconda3/envs/py36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'notebook-bundle']' returned non-zero exit status 1.
```

my env was
```
python 3.6
pip 19.2.2 
```

How can I install pydeck..?

**Comment by Pessimistress** [comment]
The master branch is our dev branch and this feature is still under developement. @ajduberstein may point you to the alpha release.

**Comment by ajduberstein** [comment]
@heumsi appreciate the interest! If you can wait a week, we'll have an alpha version you can try that will be more easily pip installable.

**Comment by ajduberstein** [comment]
@heumsi a beta is live–try `pip install pydeck`

**Comment by ajduberstein** [comment]
Assuming this is addressed–feel to re-open the issue if it's not.
