### ISSUE TITLE
Deck.gl and fusion app freezing in production and staging environments.

### ISSUE THREAD

**Issue by uParkA** [uber/deck.gl#3861]
#### Description
Hey, currently have a bug that only occurs in staging and production environments.
![wrm_prod_err](https://user-images.githubusercontent.com/53790474/68508834-6d67c800-023d-11ea-8425-c3960244c0c7.png)

I am using deck.gl, nebula.gl, and react-map-gl to render my map with layers. Locally it renders perfectly fine as expected to. When deployed to staging or production environment it deploys without crashes or errors. Once loading the application it partially loads and then freezes. Note, that the app does not even have to be loading the page that renders the map, but any page of the app. 

The web framework that I am using is Fusion.js it provides a Webpack/Babel setup.

Currently rendering from a React class component where `DeckGL` is imported from `deck.gl`, and `StaticMap` is imported from `react-map-gl`.
```
render() {
    const {height, width, viewState, selectedDeliveryZone} = this.props;
    const layers = this.getNebulaLayers(selectedDeliveryZone);
    return (
      <DeckGL
        height={height}
        layers={layers}
        width={width}
        viewState={viewState}
      >
        <StaticMap mapStyle={MapStyleURL} />
      </DeckGL>
    );
  } 
```

#### Environment :
 - Frameworks:
    - deck.gl ^7.3.4 & ^7.0.0 (tested in staging/prod with both versions)
    - nebula.gl ^0.16.0
    - react-map-gl ^5.0.12
    - fusion-core ^2.0.6
    - fusion-cli ^2.4.2
    - react ^16.10.2
 - Browser Version: 77.0.3865.90 (Official Build) (64-bit)

#### Logs
This is the only local chrome console log.
```
mapbox-gl.js:29 This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.
```
These are some stack traces when it was in production/staging

```
Error:  index.js:  undefined  is  not  an  object  (evaluating  'o.fp64.fp64LowPart')
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
  at  null.<anonymous>(https://restaurant.uber.com/v2/_static/client-vendor-f227d04fd9ff96be12d7.js:63:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
  at  null.<anonymous>(https://restaurant.uber.com/v2/_static/client-vendor-f227d04fd9ff96be12d7.js:113:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
  at  null.<anonymous>(https://restaurant.uber.com/v2/_static/client-main-bfd3147550bff7fea008.js:1:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
  at  null.<anonymous>(https://restaurant.uber.com/v2/_static/client-vendor-f227d04fd9ff96be12d7.js:113:1)
  at  null.<anonymous>(https://restaurant.uber.com/v2/_static/client-vendor-f227d04fd9ff96be12d7.js:113:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
  at  null.<anonymous>(https://restaurant.uber.com/v2/_static/client-main-bfd3147550bff7fea008.js:1:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:45:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:32:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:145:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:150:1)
```

```
Error:  index.js:  Cannot  read  property  'fp64LowPart'  of  undefined
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
  at  null.<anonymous>(/src/layers/path-marker-layer/path-marker-layer.js:4:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
  at  null.<anonymous>(/home/udocker/src/index.js:12:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
  at  null.<anonymous>(/src/lib/layers/junctions-layer.js:2:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
  at  null.<anonymous>(/home/udocker/src/index.js:10:1)
  at  null.<anonymous>(/home/udocker/web-restaurant-manager/webpack/bootstrap:79:1)
```

**Comment by Pessimistress** [comment]
Looks like the problematic import is from nebula.gl. You may want to ask in their repo as well.

We have seen issues where fusion.js applies tree shaking too aggressively and causes trouble. I'd suggest:

- use the latest deck.gl and luma.gl in your package.json
- make sure you have only one copy of deck.gl and luma.gl installed (`yarn list @deck.gl/core` and `yarn list @luma.gl/core`).

**Comment by uParkA** [comment]
> Looks like the problematic import is from nebula.gl. You may want to ask in their repo as well.
> 
> We have seen issues where fusion.js applies tree shaking too aggressively and causes trouble. I'd suggest:
> 
> * use the latest deck.gl and luma.gl in your package.json
> * make sure you have only one copy of deck.gl and luma.gl installed (`yarn list @deck.gl/core` and `yarn list @luma.gl/core`)

Currently used the latest of both dependencies and checked if there were only one copy. The only thing is should I bother to add in luma.gl if its core is already a sub dependency for deck.gl? 

I've tried both have `luma.gl` added in as a main dep and not.

**Comment by jcready** [comment]
The issue is due to a bug with Webpack's `optimization.concatenateModules`. If you update your webpack version the issue should disappear.

**Comment by uParkA** [comment]
> The issue is due to a bug with Webpack's `optimization.concatenateModules`. If you update your webpack version the issue should disappear.

I was informed that the webpack update has not occurred in fusion, so instead I added "webpack": "4.41.2" as a Resolution in the package.json. 

Unfortunately, the error still occurs :(

**Comment by uParkA** [comment]
After the new upgrading to Fusion.js release 4.2.0. The error has gone away, thank you!
