### ISSUE TITLE
Upgrading h3-js to 3.6.2 breaks h3-hexagon-layer-low-zoom test

### ISSUE THREAD

**Issue by ajduberstein** [uber/deck.gl#3893]
#### Description

Updating h3-js to h3-js@3.6.2 breaks deck.gl's testing suite.

#### Repro Steps

Updating `modules/geo-layers/package.json` to a later version of h3-js causes the issue.
Run `yarn run test browser` afterwards.

The test produces a blank screenshot, vs the previous artifact below:

![image](https://user-images.githubusercontent.com/2204757/69106092-32764900-0a22-11ea-8fe1-2bcd3afe83de.png)

#### Environment (please complete the following information):
 - Framework Version: [e.g. deck.gl 6.3.0]: 7.4.0-alpha.2
 - Browser Version: [e.g. Chrome 71.0] Chrome 78.0
 - OS: [e.g. Mac OS X 10.4] Mac OS X 10.14.6

#### Logs

```
# h3-hexagon-layer-low-zoom
not ok 5432 match: 96.85%
  ---
    operator: fail
    stack: |-
      Error: match: 96.85%
          at Test.assert [as _assert] (http://localhost:5000/test-browser.js:260968:54)
          at Test.bound [as _assert] (http://localhost:5000/test-browser.js:260820:32)
          at Test../node_modules/tape/lib/test.js.Test.fail (http://localhost:5000/test-browser.js:261061:10)
          at Test.bound [as fail] (http://localhost:5000/test-browser.js:260820:32)
          at Object.onTestFail (http://localhost:5000/test-browser.js:288152:43)
          at SnapshotTestRunner._fail (http://localhost:5000/test-browser.js:38410:22)
          at http://localhost:5000/test-browser.js:38246:14
```

**Comment by Pessimistress** [comment]
The breakage is in h3-js, created issue here: https://github.com/uber/h3-js/issues/76
