### ISSUE TITLE
"Web page was not allowed to create a WebGL context" in v4.0.0-beta5

### ISSUE THREAD

**Issue by Firenze11** [uber/deck.gl#415]
Encountering this issue a lot when using the PlotLayer. Here's the error stack:
```
"AssertionError: Failed to create WebGLRenderingContext
    at i (localhost:4700/javascripts/main-cc52f07153.js:90:15907)
    at t.value (localhost:4700/javascripts/main-cc52f07153.js:60:26235)
    at t.value (localhost:4700/javascripts/main-cc52f07153.js:60:25996)
    at r.notifyAll (localhost:4700/javascripts/main-cc52f07153.js:104:28932)
    at r.close (localhost:4700/javascripts/main-cc52f07153.js:108:11197)
    at r.closeAll (localhost:4700/javascripts/main-cc52f07153.js:109:11974)
    at r.perform (localhost:4700/javascripts/main-cc52f07153.js:109:11420)
    at o.perform (localhost:4700/javascripts/main-cc52f07153.js:109:11337)
    at o.perform (localhost:4700/javascripts/main-cc52f07153.js:108:23216)
    at Object.x [as flushBatchedUpdates] (localhost:4700/javascripts/main-cc52f07153.js:108:23385)
    at r.closeAll (localhost:4700/javascripts/main-cc52f07153.js:109:11974)
    at r.perform (localhost:4700/javascripts/main-cc52f07153.js:109:11420)
    at Object.batchedUpdates (localhost:4700/javascripts/main-cc52f07153.js:107:5999)
    at Object.l [as enqueueUpdate] (localhost:4700/javascripts/main-cc52f07153.js:108:22329)
    at r (localhost:4700/javascripts/main-cc52f07153.js:108:19731)
    at Object.enqueueSetState (localhost:4700/javascripts/main-cc52f07153.js:108:20703)
    at t.r.setState (localhost:4700/javascripts/main-cc52f07153.js:106:6141)
    at ModelStore.r._onModelChange (localhost:4700/javascripts/main-cc52f07153.js:119:18939)
    at ModelStore.r.emit (localhost:4700/javascripts/main-cc52f07153.js:65:14603)
    at ModelStore.emitChange (localhost:4700/javascripts/main-cc52f07153.js:142:31144)
    at localhost:4700/javascripts/main-cc52f07153.js:143:19052"
```

**Comment by shaojingli** [comment]
So the rendering context is not created correctly. Is it always like that? Restarting your browser might solve this...

**Comment by Firenze11** [comment]
Yeah it was always like that, and restarting doesn't help. My browser can render PlotLayer in deck.gl demo code, though. So it's a bit strange

**Comment by Firenze11** [comment]
It turned out that I cannot replicate the error any more, without changing the code or browser configuration. Will resolve the issue for now.

**Comment by Jamal8548** [comment]
I have had a similar issue with an Nvidia Quadro FX1800 but have found a workaround.

Go to chrome://flags and look for Choose ANGLE graphics backend option. I tried out each option to see if the fault occurred on every setting. It didn't thankfully, but some where much slower to render than others.

I would check the options available to you here and try out each of them. Hopefully at least one should work for you.
