### ISSUE TITLE
ShaderCache is not a constructor

### ISSUE THREAD

**Issue by ale0xb** [uber/deck.gl#728]
Hello, I pulled from master today and the project is failing: `npm test` gives this output: 
```
not ok 497 TypeError: ShaderCache is not a constructor
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [TypeError: ShaderCache is not a constructor]
    at: Test.die (/Users/alexb/Projects/deck.gl/node_modules/tape-catch/index.js:56:10)
    stack: |-
      TypeError: ShaderCache is not a constructor
          at new LayerManager (/Users/alexb/Projects/deck.gl/src/lib/layer-manager.js:70:20)
          at Object.<anonymous> (/Users/alexb/Projects/deck.gl/test/experimental/lib/effect-manager.spec.js:27:22)
          at Module._compile (module.js:569:30)
          at Module.Mp._compile (/Users/alexb/Projects/deck.gl/node_modules/reify/node/compile-hook.js:10:21)
          at Object.Module._extensions..js (module.js:580:10)
          at Module.load (module.js:503:32)
          at Module.Mp.load (/Users/alexb/Projects/deck.gl/node_modules/reify/node/runtime.js:16:23)
          at tryModuleLoad (module.js:466:12)
          at Function.Module._load (module.js:458:3)
          at Module.require (module.js:513:17)
          at Module.Mp.import (/Users/alexb/Projects/deck.gl/node_modules/reify/lib/runtime.js:75:16)
```
My guess is that the right luma.gl version is not referenced on package.json?

**Comment by ibgreen** [comment]
@ale0xb - I have published new versions of luma.gl (alpha 13) and deck.gl (alpha 14) - you may have to do a clean install.

**Comment by ale0xb** [comment]
102e65283fda5eb2e786074caaeef137f977e0aa fixed it for me. 
Thank you.
